/**
 * The Rock — exactly 60 habits (9 journey categories × balanced mix) for a 30-day × 2 tips/day trickle.
 *
 * `money_gbp` / `carbon_kg` are indicative annual figures, rounded for UX — anchored to April 2026
 * narrative in `lib/brains/constants.ts` (`MARCH_2026_ECONOMY` unit rates, `TRUTH_2026_JULY.PRICE_CAP_TYPICAL_GBP`, grid intensity 129 g/kWh).
 */
import type { RockHabit } from '@/lib/rock/types'
import { resolveRockHabitLearnUrl } from '@/lib/rock/resolveRockHabitLearnUrl'
import { formatCarbon, formatZoneCardMoney } from '@/lib/format'
import { defaultVerifiedArchitectSuppliedBy } from '@/lib/soloFocusSuppliedBy'
import { VERIFIED_SOURCE_DATE, resolvePartnerLink, formatVerifiedSourceNameFromLabel } from '@/lib/zone/verifiedRevenue'

export const ROCK_HABIT_COUNT = 60

export const ROCK_HABITS: RockHabit[] = [
  {
    slug: 'fridge-gap',
    journey_key: 'food',
    title: 'the fridge gap',
    insight:
      'Leave a finger-width gap behind the fridge so the motor can breathe — your kitchen stays cooler and the bill eases.',
    money_gbp: 18,
    carbon_kg: 12,
    provider_name: 'Love Food Hate Waste',
    learn_url: 'https://www.lovefoodhatewaste.com',
    seasons: ['spring', 'summer'],
  },
  {
    slug: 'loft-hatch-seal',
    journey_key: 'home',
    title: 'loft hatch seal',
    insight: 'Tape a foam strip round the loft hatch — stops warm air whistling up into the roof space.',
    money_gbp: 35,
    carbon_kg: 40,
    provider_name: 'EST',
    learn_url: 'https://www.energysavingtrust.org.uk/advice/reducing-home-heat-loss/',
    seasons: ['autumn', 'winter'],
  },
  {
    slug: 'router-sleep',
    journey_key: 'tech',
    title: 'router sleep',
    insight: 'Put the broadband box on a timer so it sleeps when the house does — quiet nights, smaller standby bill.',
    money_gbp: 22,
    carbon_kg: 15,
    provider_name: 'Energy Saving Trust',
    learn_url: 'https://www.energysavingtrust.org.uk/advice/electrical-appliances/',
  },
  {
    slug: 'water-butt',
    journey_key: 'waste',
    title: 'the water butt',
    insight: 'Collect rainwater for the garden to cut metered water use in summer.',
    money_gbp: 45,
    carbon_kg: 5,
    provider_name: 'Waterwise',
    learn_url: 'https://www.waterwise.org.uk/save-water/',
    seasons: ['spring', 'summer'],
  },
  {
    slug: 'speed-cap-60',
    journey_key: 'holidays',
    title: 'speed cap 60',
    insight: 'Driving at 60mph vs 70mph can improve fuel economy by up to 15%.',
    money_gbp: 210,
    carbon_kg: 300,
    provider_name: 'AA',
  },
  {
    slug: 'radiator-foil',
    journey_key: 'home',
    title: 'vertical radiator foil',
    insight: 'Reflect heat back into the room instead of into the external wall.',
    money_gbp: 28,
    carbon_kg: 35,
    provider_name: 'Screwfix',
    seasons: ['autumn', 'winter'],
  },
  {
    slug: 'air-fryer-swap',
    journey_key: 'food',
    title: 'air fryer swap',
    insight: 'Using an air fryer instead of a full oven can save ~70% electricity per meal.',
    money_gbp: 55,
    carbon_kg: 40,
    provider_name: 'Ninja',
    seasons: ['spring', 'summer'],
  },
  {
    slug: 'tablet-over-tv',
    journey_key: 'tech',
    title: 'tablet over tv',
    insight: 'Watching on a tablet uses far less energy than a 65-inch 4K television.',
    money_gbp: 32,
    carbon_kg: 20,
    provider_name: 'Sony',
  },
  {
    slug: 'bamboo-tp',
    journey_key: 'waste',
    title: 'bamboo swap',
    insight: 'Bamboo toilet paper cuts the carbon footprint of bathroom paper vs virgin pulp.',
    money_gbp: 0,
    carbon_kg: 15,
    provider_name: 'Who Gives A Crap',
  },
  {
    slug: 'smart-trvs',
    journey_key: 'home',
    title: 'smart TRVs',
    insight: 'Smart radiator valves heat only the rooms you are actually using.',
    money_gbp: 185,
    carbon_kg: 250,
    provider_name: 'tado',
    seasons: ['autumn', 'winter'],
  },
  {
    slug: 'draught-excluders',
    journey_key: 'home',
    title: 'draught excluders',
    insight: 'Fit simple door and window excluders — one of the cheapest heat saves.',
    money_gbp: 25,
    carbon_kg: 30,
    provider_name: 'EST',
    seasons: ['autumn', 'winter'],
  },
  {
    slug: 'led-everywhere',
    journey_key: 'carbon',
    title: 'LED everywhere',
    insight: 'Replace any remaining halogens with LED — instant payback on April 2026 rates.',
    money_gbp: 40,
    carbon_kg: 25,
    provider_name: 'Philips',
  },
  {
    slug: 'shower-four-min',
    journey_key: 'home',
    title: 'four minute shower',
    insight: 'Cut average shower time — less hot water is one of the fastest bill wins.',
    money_gbp: 45,
    carbon_kg: 35,
    provider_name: 'Waterwise',
  },
  {
    slug: 'wash-30c',
    journey_key: 'home',
    title: 'wash at 30°C',
    insight: 'Modern detergents work at 30°C; saves electricity every load.',
    money_gbp: 30,
    carbon_kg: 40,
    provider_name: 'Ariel',
  },
  {
    slug: 'kettle-min',
    journey_key: 'home',
    title: 'kettle minimum',
    insight: 'Only boil the water you need — repeated overfills add up yearly.',
    money_gbp: 12,
    carbon_kg: 8,
    provider_name: 'EST',
  },
  {
    slug: 'microwave-small',
    journey_key: 'food',
    title: 'microwave small heats',
    insight: 'Reheat single portions in the microwave instead of firing the full oven.',
    money_gbp: 20,
    carbon_kg: 25,
    provider_name: 'Which?',
  },
  {
    slug: 'batch-cook',
    journey_key: 'food',
    title: 'batch cook freeze',
    insight: 'Cook double portions and freeze — one oven session, two meals.',
    money_gbp: 35,
    carbon_kg: 30,
    provider_name: 'BBC Good Food',
    seasons: ['autumn', 'winter'],
  },
  {
    slug: 'veg-box',
    journey_key: 'food',
    title: 'local veg box',
    insight: 'A seasonal veg box cuts food miles and supports local growers.',
    money_gbp: 55,
    carbon_kg: 45,
    provider_name: 'Riverford',
    seasons: ['spring', 'summer', 'autumn'],
  },
  {
    slug: 'flex-monday',
    journey_key: 'food',
    title: 'plant monday',
    insight: 'One fully plant-based day a week cuts food emissions meaningfully.',
    money_gbp: 70,
    carbon_kg: 120,
    provider_name: 'Oxfam',
  },
  {
    slug: 'dishwasher-full',
    journey_key: 'home',
    title: 'dishwasher full eco',
    insight: 'Run the dishwasher only when full on eco cycle.',
    money_gbp: 22,
    carbon_kg: 18,
    provider_name: 'Bosch',
  },
  {
    slug: 'combine-trips',
    journey_key: 'travel',
    title: 'combine car trips',
    insight: 'Chain errands into one journey — cold starts burn the most fuel.',
    money_gbp: 95,
    carbon_kg: 180,
    provider_name: 'RAC',
  },
  {
    slug: 'tyre-pressure',
    journey_key: 'travel',
    title: 'tyre pressure monthly',
    insight: 'Under-inflated tyres increase drag and fuel use.',
    money_gbp: 80,
    carbon_kg: 140,
    provider_name: 'AA',
  },
  {
    slug: 'railcard',
    journey_key: 'holidays',
    title: 'annual railcard',
    insight: 'Weekend and leisure trips by train often beat driving on cost; a railcard compounds the saving.',
    money_gbp: 320,
    carbon_kg: 400,
    provider_name: 'National Rail',
  },
  {
    slug: 'e-bike-scheme',
    journey_key: 'holidays',
    title: 'e-bike schemes',
    insight: 'Salary-sacrifice e-bike schemes shine for local exploring and short hops without a car.',
    money_gbp: 400,
    carbon_kg: 350,
    provider_name: 'GOV.UK',
    seasons: ['spring', 'summer'],
  },
  {
    slug: 'cruise-control',
    journey_key: 'holidays',
    title: 'cruise on motorways',
    insight: 'Steady throttle on long runs beats constant accel/decel.',
    money_gbp: 110,
    carbon_kg: 160,
    provider_name: 'IAM RoadSmart',
  },
  {
    slug: 'preloved-fashion',
    journey_key: 'shopping',
    title: 'preloved fashion',
    insight: 'Quality second-hand cuts spend and fashion emissions.',
    money_gbp: 120,
    carbon_kg: 80,
    provider_name: 'Vinted',
  },
  {
    slug: 'repair-cafe',
    journey_key: 'shopping',
    title: 'repair cafe first',
    insight: 'Repair cafes fix small appliances before you replace.',
    money_gbp: 40,
    carbon_kg: 25,
    provider_name: 'Restart Project',
  },
  {
    slug: 'refill-stores',
    journey_key: 'shopping',
    title: 'refill stores',
    insight: 'Refill detergents and dry goods to cut packaging and cost.',
    money_gbp: 65,
    carbon_kg: 15,
    provider_name: 'Refill',
  },
  {
    slug: 'deposit-return',
    journey_key: 'waste',
    title: 'deposit return',
    insight: 'Use bottle deposit schemes where live — cash back + less waste.',
    money_gbp: 15,
    carbon_kg: 10,
    provider_name: 'Tesco',
  },
  {
    slug: 'home-compost',
    journey_key: 'waste',
    title: 'home compost',
    insight: 'Compost kitchen scraps — less bin weight, rich soil.',
    money_gbp: 0,
    carbon_kg: 45,
    provider_name: 'RHS',
    seasons: ['spring', 'summer', 'autumn'],
  },
  {
    slug: 'mps-mail',
    journey_key: 'waste',
    title: 'stop junk mail',
    insight: 'Register with MPS to cut unsolicited post.',
    money_gbp: 8,
    carbon_kg: 2,
    provider_name: 'Royal Mail',
  },
  {
    slug: 'vampire-unplug',
    journey_key: 'tech',
    title: 'unplug vampires',
    insight: 'Unplug idle chargers and standby hubs — small watts, 24/7.',
    money_gbp: 18,
    carbon_kg: 12,
    provider_name: 'EST',
  },
  {
    slug: 'laptop-eco',
    journey_key: 'tech',
    title: 'laptop low power',
    insight: 'Use battery saver / eco mode on laptops for daily use.',
    money_gbp: 14,
    carbon_kg: 10,
    provider_name: 'Microsoft',
  },
  {
    slug: 'phone-repair',
    journey_key: 'tech',
    title: 'repair not replace',
    insight: 'Screen repair beats a new phone for wallet and footprint.',
    money_gbp: 200,
    carbon_kg: 80,
    provider_name: 'iFixit',
  },
  {
    slug: 'cloud-purge',
    journey_key: 'tech',
    title: 'delete cloud junk',
    insight: 'Old backups and photos in the cloud still cost data-centre energy.',
    money_gbp: 5,
    carbon_kg: 25,
    provider_name: 'Google',
  },
  {
    slug: 'smart-meter',
    journey_key: 'carbon',
    title: 'smart meter',
    insight: 'If eligible, a smart meter helps spot waste — no extra kit cost.',
    money_gbp: 0,
    carbon_kg: 20,
    provider_name: 'Octopus',
  },
  {
    slug: 'cavity-check',
    journey_key: 'home',
    title: 'cavity wall check',
    insight: 'Book a free or subsidised survey — empty cavities leak heat.',
    money_gbp: 150,
    carbon_kg: 300,
    provider_name: 'EST',
    seasons: ['autumn', 'winter'],
  },
  {
    slug: 'floor-insulation',
    journey_key: 'home',
    title: 'floor insulation',
    insight: 'Insulate suspended floors — big comfort win on older homes.',
    money_gbp: 90,
    carbon_kg: 120,
    provider_name: 'Rockwool',
    seasons: ['autumn', 'winter'],
  },
  {
    slug: 'cylinder-jacket',
    journey_key: 'home',
    title: 'cylinder jacket',
    insight: 'Lag the hot water cylinder if it is not factory-insulated.',
    money_gbp: 55,
    carbon_kg: 60,
    provider_name: 'British Gas',
    seasons: ['autumn', 'winter'],
  },
  {
    slug: 'secondary-glaze',
    journey_key: 'carbon',
    title: 'secondary glazing',
    insight: 'Secondary panels cut drafts where full double-glaze is costly.',
    money_gbp: 120,
    carbon_kg: 140,
    provider_name: 'Mighton',
    seasons: ['autumn', 'winter'],
  },
  {
    slug: 'battery-shift',
    journey_key: 'carbon',
    title: 'battery time-shift',
    insight: 'If you have a home battery, discharge at peak price windows.',
    money_gbp: 140,
    carbon_kg: 90,
    provider_name: 'Tesla',
  },
  {
    slug: 'heat-pump-check',
    journey_key: 'carbon',
    title: 'heat pump survey',
    insight: 'Free or low-cost suitability checks before you commit.',
    money_gbp: 0,
    carbon_kg: 35,
    provider_name: 'Nesta',
  },
  {
    slug: 'ev-off-peak',
    journey_key: 'carbon',
    title: 'EV off-peak charge',
    insight: 'Charge EV on overnight or off-peak tariffs after April cap shifts.',
    money_gbp: 220,
    carbon_kg: 100,
    provider_name: 'Octopus',
  },
  {
    slug: 'green-mortgage',
    journey_key: 'money',
    title: 'green mortgage ask',
    insight: 'Ask your lender if greener retrofits unlock better rates.',
    money_gbp: 0,
    carbon_kg: 0,
    provider_name: 'Barclays',
  },
  {
    slug: 'meter-reads',
    journey_key: 'money',
    title: 'meter readings',
    insight: 'Submit reads so bills track real use — avoids estimated drift.',
    money_gbp: 35,
    carbon_kg: 0,
    provider_name: 'Ofgem',
  },
  {
    slug: 'tariff-compare',
    journey_key: 'money',
    title: 'compare every april',
    insight: 'Re-compare tariffs when the cap updates — loyalty rarely wins.',
    money_gbp: 180,
    carbon_kg: 40,
    provider_name: 'MoneySavingExpert',
  },
  {
    slug: 'direct-debit',
    journey_key: 'money',
    title: 'direct debit discount',
    insight: 'Many suppliers discount fixed monthly DD vs pay-on-bill.',
    money_gbp: 50,
    carbon_kg: 0,
    provider_name: 'Citizens Advice',
  },
  {
    slug: 'thermostat-one',
    journey_key: 'home',
    title: 'one degree down',
    insight: 'Turn the thermostat down 1°C — barely noticeable, real gas save.',
    money_gbp: 75,
    carbon_kg: 90,
    provider_name: 'Nest',
    seasons: ['autumn', 'winter'],
  },
  {
    slug: 'radiator-bleed',
    journey_key: 'home',
    title: 'bleed radiators',
    insight: 'Trapped air means cold tops and a working boiler for nothing.',
    money_gbp: 18,
    carbon_kg: 22,
    provider_name: 'EST',
    seasons: ['autumn', 'winter'],
  },
  {
    slug: 'loft-top-up',
    journey_key: 'home',
    title: 'loft top-up 300mm',
    insight: 'Top up loft insulation toward 300mm — one of the best £/kg wins.',
    money_gbp: 200,
    carbon_kg: 350,
    provider_name: 'EST',
    seasons: ['autumn', 'winter'],
  },
  {
    slug: 'curtains-dusk',
    journey_key: 'holidays',
    title: 'pretrip standby sweep',
    insight: 'Before a break, switch off standby clusters — same discipline as leaving a hotel room.',
    money_gbp: 28,
    carbon_kg: 32,
    provider_name: 'John Lewis',
  },
  {
    slug: 'line-dry-week',
    journey_key: 'holidays',
    title: 'quick-dry travel layers',
    insight: 'Quick-dry layers cut luggage weight on UK trips and tumble use when you are home.',
    money_gbp: 55,
    carbon_kg: 70,
    provider_name: 'Whirlpool',
    seasons: ['spring', 'summer'],
  },
  {
    slug: 'freezer-defrost',
    journey_key: 'food',
    title: 'defrost freezer',
    insight: 'Ice buildup makes the freezer work harder and costs more.',
    money_gbp: 22,
    carbon_kg: 15,
    provider_name: 'Hotpoint',
  },
  {
    slug: 'pan-lids',
    journey_key: 'food',
    title: 'lid on pans',
    insight: 'Lids trap steam and cut hob time — less gas or electricity.',
    money_gbp: 15,
    carbon_kg: 12,
    provider_name: 'EST',
  },
  {
    slug: 'slow-cooker',
    journey_key: 'food',
    title: 'slow cooker days',
    insight: 'One-pot slow cooking often beats oven + hob for stews.',
    money_gbp: 40,
    carbon_kg: 30,
    provider_name: 'Morphy Richards',
    seasons: ['autumn', 'winter'],
  },
  {
    slug: 'greywater-plants',
    journey_key: 'home',
    title: 'greywater plants',
    insight: 'Reuse cooled bath water on hardy plants — less tap in summer.',
    money_gbp: 0,
    carbon_kg: 8,
    provider_name: 'RHS',
    seasons: ['spring', 'summer'],
  },
  {
    slug: 'jeans-cold',
    journey_key: 'shopping',
    title: 'jeans cold wash',
    insight: 'Wash denim cold and less often — lasts longer too.',
    money_gbp: 20,
    carbon_kg: 25,
    provider_name: "Levi's",
  },
  {
    slug: 'library-ebooks',
    journey_key: 'tech',
    title: 'library ebooks',
    insight: 'Borrow ebooks and audiobooks — near-zero marginal footprint.',
    money_gbp: 30,
    carbon_kg: 15,
    provider_name: 'Libraries',
  },
  {
    slug: 'print-double',
    journey_key: 'tech',
    title: 'print double-sided',
    insight: 'If you must print, default to duplex — halves paper and energy.',
    money_gbp: 8,
    carbon_kg: 10,
    provider_name: 'HP',
  },
  {
    slug: 'pension-esg',
    journey_key: 'money',
    title: 'pension ESG check',
    insight: 'See if your default pension fund offers a lower-carbon option.',
    money_gbp: 0,
    carbon_kg: 5,
    provider_name: 'Which?',
  },
]

if (ROCK_HABITS.length !== ROCK_HABIT_COUNT) {
  console.warn(`[Rock] Expected ${ROCK_HABIT_COUNT} habits, got ${ROCK_HABITS.length}`)
}

/** Every habit gets a topic-aligned https offer when catalog omits `learn_url`. */
for (const habit of ROCK_HABITS) {
  habit.learn_url = resolveRockHabitLearnUrl(habit)
}

export const ROCK_BY_SLUG = new Map(ROCK_HABITS.map((h) => [h.slug, h]))

export function rockCardId(slug: string): string {
  return `rock-${slug}`
}

export function sumRockLikedImpact(likedCardIds: readonly string[]): { money: number; carbon: number } {
  let money = 0
  let carbon = 0
  for (const id of likedCardIds) {
    if (!id.startsWith('rock-')) continue
    const h = ROCK_BY_SLUG.get(id.slice(5))
    if (h) {
      money += h.money_gbp
      carbon += h.carbon_kg
    }
  }
  return { money, carbon }
}

export function habitToTipCard(h: RockHabit): import('@/lib/logic/zone').ZoneTipCard {
  const learnUrl = resolveRockHabitLearnUrl(h)
  const sourceLabel = `source. ${h.provider_name}`
  const source_name = formatVerifiedSourceNameFromLabel(h.provider_name)
  const partner_link = resolvePartnerLink({
    journey: h.journey_key,
    actionType: 'learn',
    needsSwitching: false,
    learnUrl,
    sourceUrl: learnUrl,
    variant: 'tip',
  })
  return {
    id: rockCardId(h.slug),
    variant: 'card-compact',
    title: h.title,
    journey_key: h.journey_key,
    category: h.journey_key,
    data: {
      money: formatZoneCardMoney(Math.max(0, h.money_gbp)),
      carbon: formatCarbon(h.carbon_kg),
    },
    explanation: [h.insight],
    source: learnUrl,
    sourceLabel,
    source_name,
    source_date: VERIFIED_SOURCE_DATE,
    partner_link,
    architectSuppliedBy: defaultVerifiedArchitectSuppliedBy({
      sourceLabel,
      sourceUrl: learnUrl,
    }),
    actions: {
      actionType: 'learn',
      learnUrl,
    },
  }
}
