/**
 * The action library — seeded with the renter + TIGHT column first, deliberately.
 *
 * That column is the hardest one to fill: you can't change the building, and you can't spend
 * money, so it has the fewest available moves and the least room for the "just buy a better one"
 * advice that pads out the easy columns. If twelve genuinely strong actions exist here, every
 * other column is easier. Building it first also stops the whole system quietly being designed
 * around a homeowner with spare cash, which is the trap the old 12-category wall fell into.
 *
 * Every entry was verified against a live source on the date in `verifiedOn`. Two things that
 * check caught, both of which would have shipped as confident nonsense:
 *   - Warm Home Discount was CLOSED at time of writing (reopens Oct 2026) and is automatic in
 *     England and Wales — so "apply now" would be wrong twice over.
 *   - The Household Support Fund ENDED on 31 March 2026, replaced by the Crisis and Resilience
 *     Fund, so it is deliberately absent rather than pointing at a dead scheme.
 *
 * Rule for adding anything here: if the URL goes to something you read rather than something you
 * do, it is not an action and does not belong.
 */

import type { ZoneAction } from '@/lib/actions/actionTypes'
import { isValidJourneyId } from '@/lib/journeys'

/**
 * Card slugs the `/zone/card/[journeyKey]` route must resolve. A ranked wall can return several
 * cards from the same bucket, so cards are addressed by action id; the legacy per-category slugs
 * stay valid for the guest wall.
 */
export function isValidZoneCardSlug(slug: string): boolean {
  const s = String(slug ?? '').trim()
  if (!s) return false
  if (isValidJourneyId(s)) return true
  return ZONE_ACTIONS.some((a) => a.id === s)
}

export const ZONE_ACTIONS: ZoneAction[] = [
  // ---------------------------------------------------------------------------------------
  // CLAIM — entitlements. Highest value per slot, cost nothing, and are massively underclaimed.
  // ---------------------------------------------------------------------------------------
  {
    id: 'benefits-entitlement-check',
    action: 'Check what you are owed',
    detail:
      'Around 7 million UK households miss entitlements worth an average £3,428 a year. The check is free and takes about ten minutes.',
    verb: 'CLAIM',
    cost: 'FREE',
    recurrence: 'ANNUAL',
    bucket: 'money',
    valueGbp: 3428,
    valueKg: 0,
    url: 'https://benefits-calculator.turn2us.org.uk/',
    source: 'Policy in Practice, Missing Out 2025 (£24bn unclaimed, ~7m households); Turn2us calculator',
    verifiedOn: '2026-07-31',
    gates: { financial: ['TIGHT', 'GETTING_BY'] },
    // Unlocks every other means-tested action, so it should lead rather than land at slot nine.
    priorityBoost: 40,
  },
  {
    id: 'council-tax-reduction',
    action: 'Apply for Council Tax Reduction',
    detail:
      'Worth up to 100% off your bill on a low income. It is never applied automatically and your council will not offer it — you have to apply.',
    verb: 'CLAIM',
    cost: 'FREE',
    recurrence: 'ONCE',
    bucket: 'money',
    valueGbp: 1200,
    valueKg: 0,
    url: 'https://www.gov.uk/apply-council-tax-reduction',
    source: 'GOV.UK Council Tax Reduction; schemes are council-run and vary by area',
    verifiedOn: '2026-07-31',
    gates: { financial: ['TIGHT', 'GETTING_BY'] },
    priorityBoost: 30,
  },
  {
    id: 'single-person-council-tax',
    action: 'Claim the single-adult discount',
    detail:
      'If you are the only adult counted at your address, 25% comes off your Council Tax. It is not applied automatically.',
    verb: 'CLAIM',
    cost: 'FREE',
    recurrence: 'ONCE',
    bucket: 'money',
    valueGbp: 500,
    valueKg: 0,
    url: 'https://www.gov.uk/apply-for-council-tax-discount',
    source: 'GOV.UK Council Tax discounts — 25% single person discount',
    verifiedOn: '2026-07-31',
    requires: { household: ['ALONE'] },
    priorityBoost: 25,
  },
  {
    id: 'healthy-start-card',
    action: 'Get a Healthy Start card',
    detail:
      'Up to £483 a year for a baby under one, or £241.80 for pregnancy and ages one to four, loaded onto a card for milk, fruit and veg.',
    verb: 'CLAIM',
    cost: 'FREE',
    recurrence: 'ONCE',
    bucket: 'food',
    valueGbp: 483,
    valueKg: 0,
    url: 'https://www.healthystart.nhs.uk/how-to-apply/',
    source: 'NHS Healthy Start — rates from April 2026 (£483 under 1; £241.80 ages 1-4/pregnancy)',
    verifiedOn: '2026-07-31',
    // Needs an actual under-5 (or pregnancy, which onboarding doesn't ask). `requires`, not
    // `gates`: if we don't know there's a small child, we must not claim they can get this.
    requires: { children: ['UNDER_5', 'BOTH'] },
    gates: { financial: ['TIGHT', 'GETTING_BY'] },
  },
  {
    id: 'free-school-meals',
    action: 'Apply for free school meals',
    detail:
      'Saves roughly £500 a year per child and also unlocks extra funding for their school. Applying takes a few minutes.',
    verb: 'CLAIM',
    cost: 'FREE',
    recurrence: 'ONCE',
    bucket: 'food',
    valueGbp: 500,
    valueKg: 0,
    url: 'https://www.gov.uk/apply-free-school-meals',
    source: 'GOV.UK apply for free school meals',
    verifiedOn: '2026-07-31',
    // Needs a school-age child specifically — an under-5 household gets nothing from this.
    requires: { children: ['SCHOOL_AGE', 'BOTH'] },
    gates: { financial: ['TIGHT', 'GETTING_BY'] },
  },
  {
    id: 'nhs-low-income-scheme',
    action: 'Apply to the NHS Low Income Scheme',
    detail:
      'An HC2 certificate means free prescriptions, dental treatment and eye tests. You can qualify while working.',
    verb: 'CLAIM',
    cost: 'FREE',
    recurrence: 'ANNUAL',
    bucket: 'money',
    valueGbp: 300,
    valueKg: 0,
    url: 'https://www.nhsbsa.nhs.uk/nhs-low-income-scheme',
    source: 'NHSBSA NHS Low Income Scheme — HC2 full help, HC3 partial help',
    verifiedOn: '2026-07-31',
    gates: { financial: ['TIGHT', 'GETTING_BY'] },
  },
  {
    id: 'watersure-cap',
    action: 'Cap your water bill with WaterSure',
    detail:
      'Caps your metered bill at the regional average if you claim a qualifying benefit and either have three or more children or a medical need.',
    verb: 'CLAIM',
    cost: 'FREE',
    recurrence: 'ANNUAL',
    bucket: 'water',
    valueGbp: 200,
    valueKg: 0,
    url: 'https://www.citizensadvice.org.uk/consumer/water/problems-with-paying-your-water-bill/watersure-scheme-help-with-paying-water-bills/',
    source: 'Citizens Advice WaterSure — requires meter plus qualifying benefit plus high essential use',
    verifiedOn: '2026-07-31',
    gates: { financial: ['TIGHT', 'GETTING_BY'] },
  },
  {
    id: 'warm-home-discount',
    action: 'Line up your Warm Home Discount',
    detail:
      '£150 off your electricity bill. In England and Wales it is automatic on a qualifying benefit — check your supplier takes part before the scheme reopens.',
    verb: 'CLAIM',
    cost: 'FREE',
    recurrence: 'ANNUAL',
    bucket: 'utilities',
    valueGbp: 150,
    valueKg: 0,
    url: 'https://www.gov.uk/the-warm-home-discount-scheme',
    source: 'GOV.UK / Ofgem Warm Home Discount — scheme year 16 runs 1 Apr 2026 to 31 Mar 2027',
    verifiedOn: '2026-07-31',
    gates: { financial: ['TIGHT', 'GETTING_BY'] },
    // Closed at time of writing, reopening October 2026 — surfacing it earlier would tell people
    // to claim something they cannot currently claim.
    window: { months: [9, 10, 11, 12, 1, 2, 3], reviewBy: '2027-03-31' },
  },
  {
    id: 'priority-services-register',
    action: 'Join the Priority Services Register',
    detail:
      'Free from every energy supplier. Gets you priority reconnection, free meter moves and advance warning of outages.',
    verb: 'CLAIM',
    cost: 'FREE',
    recurrence: 'ONCE',
    bucket: 'utilities',
    valueGbp: 0,
    valueKg: 0,
    url: 'https://www.ofgem.gov.uk/information-consumers/energy-advice-households/getting-extra-help-priority-services-register',
    source: 'Ofgem Priority Services Register — free scheme run by suppliers',
    verifiedOn: '2026-07-31',
    gates: { financial: ['TIGHT', 'GETTING_BY'] },
  },

  // ---------------------------------------------------------------------------------------
  // SWITCH — free to do, permanent saving, and available to renters.
  // ---------------------------------------------------------------------------------------
  {
    id: 'social-broadband-tariff',
    action: 'Move to a social broadband tariff',
    detail:
      'From about £12.50 a month on a qualifying benefit, with no mid-contract price rises. Only 8.6% of eligible homes have taken one.',
    verb: 'SWITCH',
    cost: 'FREE',
    recurrence: 'ONCE',
    bucket: 'tech',
    valueGbp: 200,
    valueKg: 0,
    url: 'https://www.ofcom.org.uk/phones-and-broadband/saving-money/social-tariffs',
    source: 'Ofcom social tariffs — 532,000 of 6.2m eligible households taking one (8.6%), Feb 2026',
    verifiedOn: '2026-07-31',
    gates: { financial: ['TIGHT', 'GETTING_BY'] },
    priorityBoost: 20,
  },
  {
    id: 'water-meter-switch',
    action: 'Check if a water meter pays',
    detail:
      'Free to fit, and you can switch back within two years. Best if you have more bedrooms than people. Renters can do this without the landlord.',
    verb: 'SWITCH',
    cost: 'FREE',
    recurrence: 'ONCE',
    bucket: 'water',
    valueGbp: 100,
    valueKg: 0,
    url: 'https://www.ccw.org.uk/save-money-and-water/water-meter-calculator/',
    source: 'CCW water meter calculator — free install, 24-month switch back, renters need 6+ month lease',
    verifiedOn: '2026-07-31',
    // Loop-unlocked: hidden until the water nudge is answered, so answering it produces a card.
    requires: { loop: { water_meter_save: ['NOT YET', 'CHECK', 'SHOW ME'] } },
  },
  {
    id: 'energy-tariff-compare',
    action: 'Compare your energy tariff',
    detail:
      'Standing charges and unit rates vary by supplier and region. Comparing costs nothing and switching is free.',
    verb: 'SWITCH',
    cost: 'FREE',
    recurrence: 'ANNUAL',
    bucket: 'utilities',
    valueGbp: 120,
    valueKg: 0,
    url: 'https://www.moneysavingexpert.com/cheapenergyclub/',
    source: 'MSE Cheap Energy Club',
    verifiedOn: '2026-07-31',
    requires: { loop: { utilities_supplier_switch: ['NOT YET', 'COMPARE', 'SHOW ME'] } },
  },

  // ---------------------------------------------------------------------------------------
  // DO — free behaviour. Lowest £ per slot, so these rank last and act as the safety net that
  // stops any column ever coming up short.
  // ---------------------------------------------------------------------------------------
  {
    id: 'submit-meter-reading',
    action: 'Send a meter reading today',
    detail:
      'Estimated bills routinely run high. One reading forces your account back onto what you actually used.',
    verb: 'DO',
    cost: 'FREE',
    recurrence: 'ONGOING',
    bucket: 'utilities',
    valueGbp: 60,
    valueKg: 0,
    url: 'https://www.citizensadvice.org.uk/consumer/energy/energy-supply/problems-with-your-energy-supply/problems-with-your-energy-bill/',
    source: 'Citizens Advice — energy billing and meter readings',
    verifiedOn: '2026-07-31',
  },
  {
    id: 'heating-controls-timing',
    action: 'Set heating to hours you are home',
    detail:
      'Costs nothing and needs no permission from a landlord. Heating an empty flat is the most common avoidable spend in winter.',
    verb: 'DO',
    cost: 'FREE',
    recurrence: 'ONGOING',
    bucket: 'home',
    valueGbp: 80,
    valueKg: 300,
    url: 'https://energysavingtrust.org.uk/advice/thermostats-and-heating-controls/',
    source: 'Energy Saving Trust — thermostats and heating controls',
    verifiedOn: '2026-07-31',
    window: { months: [10, 11, 12, 1, 2, 3] },
  },
  {
    id: 'surplus-food-app',
    action: 'Pick up surplus food nearby',
    detail:
      'Shops and cafes sell unsold food at about a third of the price at closing time through Too Good To Go.',
    verb: 'DO',
    cost: 'FREE',
    recurrence: 'ONGOING',
    bucket: 'food',
    valueGbp: 150,
    valueKg: 100,
    url: 'https://www.toogoodtogo.com/en-gb',
    source: 'Too Good To Go UK — surplus food marketplace',
    verifiedOn: '2026-07-31',
  },
  {
    id: 'freegle-local-reuse',
    action: 'Get what you need free locally',
    detail:
      'Freegle has 4 million UK members giving away furniture, appliances and household kit rather than tipping it.',
    verb: 'DO',
    cost: 'FREE',
    recurrence: 'ONGOING',
    bucket: 'waste',
    valueGbp: 120,
    valueKg: 80,
    url: 'https://www.ilovefreegle.org/find',
    source: 'Freegle — UK reuse network, registered charity XT32865',
    verifiedOn: '2026-07-31',
    excludes: { loop: { waste_compost: ['YES'] } },
  },
  {
    id: 'repair-not-replace',
    action: 'Get it repaired free first',
    detail:
      'Community repair events fix laptops, kettles and phones for nothing, run by volunteers across the UK.',
    verb: 'DO',
    cost: 'FREE',
    recurrence: 'ONGOING',
    bucket: 'shopping',
    valueGbp: 100,
    valueKg: 60,
    url: 'https://therestartproject.org/parties/',
    source: 'The Restart Project — community repair events directory',
    verifiedOn: '2026-07-31',
    requires: { loop: { shopping_repair_first: ['NOT YET', 'YES', 'HOW'] } },
  },


  // =========================================================================================
  // STUDENT — `employment` was asked at onboarding and used by nothing, so every student got
  // the same wall as everyone else despite having a genuinely distinct set of entitlements.
  // =========================================================================================
  {
    id: 'student-council-tax-exemption',
    action: 'Get your student council tax exemption',
    detail:
      'An all-student household pays no Council Tax at all. Outside halls it is never automatic — you have to send them your student certificate.',
    verb: 'CLAIM',
    cost: 'FREE',
    recurrence: 'ANNUAL',
    bucket: 'money',
    valueGbp: 1400,
    valueKg: 0,
    url: 'https://www.gov.uk/council-tax/discounts-for-full-time-students',
    source: 'GOV.UK council tax student discounts — full exemption for all-student households; course 1yr+ and 21hrs/wk',
    verifiedOn: '2026-07-31',
    requires: { employment: ['STUDENT'] },
    priorityBoost: 35,
  },
  {
    id: 'student-railcard',
    action: 'Get a 16-25 Railcard',
    detail: 'A third off rail fares for £30 a year. Pays for itself in roughly two return trips.',
    verb: 'BUY',
    cost: 'LOW',
    recurrence: 'ANNUAL',
    bucket: 'travel',
    valueGbp: 167,
    valueKg: 150,
    url: 'https://www.16-25railcard.co.uk/',
    source: 'National Rail 16-25 Railcard — £30/yr, 1/3 off',
    verifiedOn: '2026-07-31',
    gates: { employment: ['STUDENT'] },
  },
  {
    id: 'student-totum-discount',
    action: 'Get a student discount card',
    detail: 'TOTUM covers supermarket, travel and high-street discounts that stack with student pricing.',
    verb: 'BUY',
    cost: 'LOW',
    recurrence: 'ANNUAL',
    bucket: 'shopping',
    valueGbp: 120,
    valueKg: 0,
    url: 'https://www.totum.com/',
    source: 'TOTUM (NUS) student discount card',
    verifiedOn: '2026-07-31',
    gates: { employment: ['STUDENT'] },
  },
  {
    id: 'student-hardship-fund',
    action: 'Ask your uni for hardship funding',
    detail:
      'Every UK university holds a hardship fund. It is a grant, not a loan, and most goes unspent each year because nobody applies.',
    verb: 'CLAIM',
    cost: 'FREE',
    recurrence: 'ANNUAL',
    bucket: 'money',
    valueGbp: 500,
    valueKg: 0,
    url: 'https://www.gov.uk/extra-money-pay-university',
    source: 'GOV.UK extra money to pay for university — hardship funds administered by institutions',
    verifiedOn: '2026-07-31',
    requires: { employment: ['STUDENT'] },
    gates: { financial: ['TIGHT', 'GETTING_BY'] },
    priorityBoost: 20,
  },

  // =========================================================================================
  // BETWEEN JOBS — the cohort with the most to gain and, before this, nothing addressed to them.
  // =========================================================================================
  {
    id: 'energy-trust-debt-grant',
    action: 'Apply to clear energy debt',
    detail:
      'Grants up to £2,000 paid straight to your supplier. You do NOT have to be a British Gas customer to apply.',
    verb: 'CLAIM',
    cost: 'FREE',
    recurrence: 'ANNUAL',
    bucket: 'utilities',
    valueGbp: 2000,
    valueKg: 0,
    url: 'https://britishgasenergytrust.org.uk/grants-available/',
    source: 'British Gas Energy Trust — up to £2,000, open to non-BG customers, needs money-advice referral, savings under £1,000',
    verifiedOn: '2026-07-31',
    gates: { financial: ['TIGHT'] },
    priorityBoost: 30,
  },
  {
    id: 'new-style-jsa',
    action: 'Check New Style JSA',
    detail:
      'Based on your National Insurance record, not your savings or your partner’s income — so people often skip it assuming they would fail a means test.',
    verb: 'CLAIM',
    cost: 'FREE',
    recurrence: 'ANNUAL',
    bucket: 'money',
    valueGbp: 900,
    valueKg: 0,
    url: 'https://www.gov.uk/guidance/new-style-jobseekers-allowance',
    source: 'GOV.UK New Style JSA — contribution-based, not means-tested',
    verifiedOn: '2026-07-31',
    requires: { employment: ['BETWEEN_JOBS'] },
    priorityBoost: 25,
  },
  {
    id: 'jobcentre-travel-discount',
    action: 'Get the Jobcentre travel discount',
    detail: 'Up to 50% off rail and some bus travel while claiming and looking for work. Ask your work coach.',
    verb: 'CLAIM',
    cost: 'FREE',
    recurrence: 'ANNUAL',
    bucket: 'travel',
    valueGbp: 200,
    valueKg: 80,
    url: 'https://www.gov.uk/jobseekers-allowance/what-youll-get',
    source: 'Jobcentre Plus Travel Discount Card — issued via work coach',
    verifiedOn: '2026-07-31',
    requires: { employment: ['BETWEEN_JOBS'] },
  },
  {
    id: 'budgeting-advance',
    action: 'Ask for a Budgeting Advance',
    detail:
      'An interest-free advance on Universal Credit for essentials like a cooker or work clothes, repaid from future payments.',
    verb: 'CLAIM',
    cost: 'FREE',
    recurrence: 'ANNUAL',
    bucket: 'money',
    valueGbp: 348,
    valueKg: 0,
    url: 'https://www.gov.uk/universal-credit/get-an-advance-first-payment',
    source: 'GOV.UK Universal Credit Budgeting Advance — interest free',
    verifiedOn: '2026-07-31',
    gates: { financial: ['TIGHT'], employment: ['BETWEEN_JOBS'] },
  },

  // =========================================================================================
  // RETIRED — pension-age entitlements are among the most underclaimed money in the UK.
  // =========================================================================================
  {
    id: 'pension-credit',
    action: 'Check Pension Credit',
    detail:
      'Tops up weekly income and is the gateway to a free TV licence, council tax help and the Warm Home Discount. Hundreds of thousands who qualify never claim.',
    verb: 'CLAIM',
    cost: 'FREE',
    recurrence: 'ANNUAL',
    bucket: 'money',
    valueGbp: 3900,
    valueKg: 0,
    url: 'https://www.gov.uk/pension-credit/how-to-claim',
    source: 'GOV.UK Pension Credit — passport benefit for TV licence, council tax and WHD',
    verifiedOn: '2026-07-31',
    requires: { age: ['RETIRED'] },
    priorityBoost: 45,
  },
  {
    id: 'attendance-allowance',
    action: 'Check Attendance Allowance',
    detail:
      'Not means-tested and not affected by savings. For state pension age with a health condition needing help or supervision.',
    verb: 'CLAIM',
    cost: 'FREE',
    recurrence: 'ANNUAL',
    bucket: 'money',
    valueGbp: 3800,
    valueKg: 0,
    url: 'https://www.gov.uk/attendance-allowance/how-to-claim',
    source: 'GOV.UK Attendance Allowance — non means-tested, pension age',
    verifiedOn: '2026-07-31',
    requires: { age: ['RETIRED'] },
    priorityBoost: 30,
  },
  {
    id: 'older-persons-bus-pass',
    action: 'Get your free bus pass',
    detail: 'Free off-peak travel across England at state pension age, and from 60 in London, Wales and Scotland.',
    verb: 'CLAIM',
    cost: 'FREE',
    recurrence: 'ONCE',
    bucket: 'travel',
    valueGbp: 300,
    valueKg: 200,
    url: 'https://www.gov.uk/apply-for-elderly-person-bus-pass',
    source: 'GOV.UK older person’s bus pass — eligibility varies by nation',
    verifiedOn: '2026-07-31',
    requires: { age: ['RETIRED'] },
  },
  {
    id: 'senior-railcard',
    action: 'Get a Senior Railcard',
    detail: 'A third off fares from 60 for £30 a year, or £70 for three years.',
    verb: 'BUY',
    cost: 'LOW',
    recurrence: 'ANNUAL',
    bucket: 'travel',
    valueGbp: 167,
    valueKg: 150,
    url: 'https://www.senior-railcard.co.uk/',
    source: 'Senior Railcard — £30/yr or £70 for 3 years, 1/3 off',
    verifiedOn: '2026-07-31',
    gates: { age: ['RETIRED'] },
  },

  // =========================================================================================
  // HEATING — `heating` was asked and used by one action. Gas and electric homes have almost
  // nothing in common in what actually saves money.
  // =========================================================================================
  {
    id: 'boiler-flow-temperature',
    action: 'Turn your boiler flow temp down',
    detail:
      'Setting a combi boiler flow to about 60C makes it condense properly. Costs nothing, changes nothing you can feel, and needs no landlord permission.',
    verb: 'DO',
    cost: 'FREE',
    recurrence: 'ONCE',
    bucket: 'home',
    valueGbp: 100,
    valueKg: 300,
    url: 'https://www.moneysavingexpert.com/utilities/reduce-boiler-flow-temperature/',
    source: 'MSE boiler flow temperature guide — combi boilers only',
    verifiedOn: '2026-07-31',
    requires: { heating: ['GAS', 'MIX'] },
    priorityBoost: 15,
  },
  {
    id: 'bleed-radiators',
    action: 'Bleed your radiators',
    detail: 'Cold patches at the top mean trapped air and a boiler working harder than it needs to. Free, takes ten minutes.',
    verb: 'DO',
    cost: 'FREE',
    recurrence: 'ANNUAL',
    bucket: 'home',
    valueGbp: 60,
    valueKg: 150,
    url: 'https://energysavingtrust.org.uk/advice/thermostats-and-heating-controls/',
    source: 'Energy Saving Trust heating controls guidance',
    verifiedOn: '2026-07-31',
    requires: { heating: ['GAS', 'MIX'] },
    window: { months: [9, 10, 11, 12, 1, 2, 3] },
  },
  {
    id: 'economy-7-check',
    action: 'Check if Economy 7 suits you',
    detail:
      'Electrically heated homes often sit on the wrong tariff. A time-of-use rate only pays if most of your usage is overnight — worth checking either way.',
    verb: 'SWITCH',
    cost: 'FREE',
    recurrence: 'ANNUAL',
    bucket: 'utilities',
    valueGbp: 150,
    valueKg: 0,
    url: 'https://www.moneysavingexpert.com/cheapenergyclub/',
    source: 'MSE Cheap Energy Club — Economy 7 comparison',
    verifiedOn: '2026-07-31',
    requires: { heating: ['ELECTRIC'] },
    priorityBoost: 15,
  },
  {
    id: 'heat-the-person-not-room',
    action: 'Heat yourself, not the whole flat',
    detail:
      'An electric throw costs pennies an hour against pounds for storage heating. The cheapest winter change for an all-electric home.',
    verb: 'BUY',
    cost: 'LOW',
    recurrence: 'ONCE',
    bucket: 'home',
    valueGbp: 180,
    valueKg: 400,
    url: 'https://energysavingtrust.org.uk/advice/reducing-home-heat-loss/',
    source: 'Energy Saving Trust — targeted vs whole-space heating',
    verifiedOn: '2026-07-31',
    gates: { heating: ['ELECTRIC'] },
    window: { months: [10, 11, 12, 1, 2, 3] },
  },
  {
    id: 'radiator-reflector-panels',
    action: 'Put foil behind your radiators',
    detail: 'Reflects heat back into the room instead of into an external wall. Removable, so renters can do it.',
    verb: 'BUY',
    cost: 'LOW',
    recurrence: 'ONCE',
    bucket: 'home',
    valueGbp: 45,
    valueKg: 110,
    url: 'https://energysavingtrust.org.uk/advice/reducing-home-heat-loss/',
    source: 'Energy Saving Trust — radiator reflector panels',
    verifiedOn: '2026-07-31',
    gates: { heating: ['GAS', 'MIX'] },
  },
  {
    id: 'draught-proofing-renter-safe',
    action: 'Draught-proof doors and windows',
    detail: 'Self-adhesive strips and a door brush cost a few pounds, peel off when you move, and need nobody’s permission.',
    verb: 'BUY',
    cost: 'LOW',
    recurrence: 'ONCE',
    bucket: 'home',
    valueGbp: 90,
    valueKg: 250,
    url: 'https://energysavingtrust.org.uk/advice/reducing-home-heat-loss/',
    source: 'Energy Saving Trust — draught-proofing',
    verifiedOn: '2026-07-31',
    window: { months: [9, 10, 11, 12, 1, 2] },
  },
  {
    id: 'smart-meter-install',
    action: 'Book a free smart meter',
    detail: 'Ends estimated billing and is installed free by your supplier. Renters can request one without the landlord.',
    verb: 'SWITCH',
    cost: 'FREE',
    recurrence: 'ONCE',
    bucket: 'utilities',
    valueGbp: 70,
    valueKg: 100,
    url: 'https://www.gov.uk/guidance/smart-meters-how-they-work',
    source: 'GOV.UK smart meters — free installation via supplier',
    verifiedOn: '2026-07-31',
  },

  // =========================================================================================
  // TRANSPORT — `transport` was asked and used by one action.
  // =========================================================================================
  {
    id: 'car-tyre-pressure',
    action: 'Check your tyre pressures',
    detail: 'Under-inflated tyres burn measurably more fuel and wear out sooner. Free at most forecourts.',
    verb: 'DO',
    cost: 'FREE',
    recurrence: 'ONGOING',
    bucket: 'travel',
    valueGbp: 70,
    valueKg: 120,
    url: 'https://www.gov.uk/government/publications/tyre-safety-and-maintenance',
    source: 'GOV.UK tyre safety and maintenance',
    verifiedOn: '2026-07-31',
    requires: { transport: ['CAR', 'MIX'] },
  },
  {
    id: 'fuel-price-check',
    action: 'Check fuel prices before filling up',
    detail: 'Forecourt prices vary by several pence a litre within the same town. The comparison is free.',
    verb: 'DO',
    cost: 'FREE',
    recurrence: 'ONGOING',
    bucket: 'travel',
    valueGbp: 90,
    valueKg: 0,
    url: 'https://www.petrolprices.com/',
    source: 'PetrolPrices UK forecourt comparison',
    verifiedOn: '2026-07-31',
    requires: { transport: ['CAR', 'MIX'] },
  },
  {
    id: 'car-insurance-never-autorenew',
    action: 'Never auto-renew your car insurance',
    detail:
      'Renewal quotes are routinely higher than new-customer prices for the identical policy. Rules now force your old price to be shown next to the new one.',
    verb: 'SWITCH',
    cost: 'FREE',
    recurrence: 'ANNUAL',
    bucket: 'travel',
    valueGbp: 250,
    valueKg: 0,
    url: 'https://www.moneysavingexpert.com/insurance/car-insurance/',
    source: 'MSE car insurance — FCA rules require renewal price disclosure',
    verifiedOn: '2026-07-31',
    requires: { transport: ['CAR', 'MIX'] },
    priorityBoost: 15,
  },
  {
    id: 'cycle-to-work-scheme',
    action: 'Use Cycle to Work',
    detail: 'Buy a bike from gross salary, saving roughly a quarter to a third of the cost. Employer-run.',
    verb: 'BUY',
    cost: 'HIGH',
    recurrence: 'ONCE',
    bucket: 'travel',
    valueGbp: 300,
    valueKg: 300,
    url: 'https://www.gov.uk/government/publications/cycle-to-work-scheme-implementation-guidance',
    source: 'GOV.UK Cycle to Work implementation guidance — salary sacrifice',
    verifiedOn: '2026-07-31',
    requires: { employment: ['EMPLOYED'] },
    gates: { transport: ['BIKE', 'MIX', 'CAR'] },
  },
  {
    id: 'bus-fare-cap',
    action: 'Check the capped bus fare',
    detail: 'A national single-fare cap applies on most English bus routes outside London. Worth knowing before buying a longer ticket.',
    verb: 'DO',
    cost: 'FREE',
    recurrence: 'ANNUAL',
    bucket: 'travel',
    valueGbp: 120,
    valueKg: 0,
    url: 'https://www.gov.uk/government/publications/get-around-for-2-with-the-bus-fare-cap',
    source: 'GOV.UK bus fare cap — England outside London',
    verifiedOn: '2026-07-31',
    gates: { transport: ['PUBLIC', 'MIX'] },
  },

  // =========================================================================================
  // HOUSEHOLD, WASH and general free money — deepen the pool so ranking has real choice.
  // =========================================================================================
  {
    id: 'council-tax-band-challenge',
    action: 'Check your council tax band',
    detail:
      'Bands were set in 1991 on rapid drive-by valuations and plenty are simply wrong. Checking is free and a successful challenge is backdated.',
    verb: 'CLAIM',
    cost: 'FREE',
    recurrence: 'ONCE',
    bucket: 'money',
    valueGbp: 400,
    valueKg: 0,
    url: 'https://www.gov.uk/challenge-council-tax-band',
    source: 'GOV.UK challenge your Council Tax band — refunds backdated to occupancy',
    verifiedOn: '2026-07-31',
    priorityBoost: 15,
  },
  {
    id: 'marriage-allowance',
    action: 'Claim Marriage Allowance',
    detail:
      'If one of you earns under the personal allowance you can transfer part of it, and claims can be backdated four years.',
    verb: 'CLAIM',
    cost: 'FREE',
    recurrence: 'ONCE',
    bucket: 'money',
    valueGbp: 252,
    valueKg: 0,
    url: 'https://www.gov.uk/marriage-allowance/how-to-apply',
    source: 'GOV.UK Marriage Allowance — £252/yr, backdatable 4 years',
    verifiedOn: '2026-07-31',
    requires: { household: ['COUPLE'] },
  },
  {
    id: 'water-social-tariff',
    action: 'Ask about a water social tariff',
    detail:
      'Separate from WaterSure and usually more generous. Every company runs one, and take-up is low because they are barely advertised.',
    verb: 'CLAIM',
    cost: 'FREE',
    recurrence: 'ANNUAL',
    bucket: 'water',
    valueGbp: 160,
    valueKg: 0,
    url: 'https://www.ccw.org.uk/save-money-and-water/help-with-bills/',
    source: 'CCW help with bills — company social tariffs',
    verifiedOn: '2026-07-31',
    gates: { financial: ['TIGHT', 'GETTING_BY'] },
  },
  {
    id: 'mobile-social-tariff',
    action: 'Switch to a social mobile tariff',
    detail: 'Around £10 a month on a qualifying benefit, with no mid-contract price rises.',
    verb: 'SWITCH',
    cost: 'FREE',
    recurrence: 'ONCE',
    bucket: 'tech',
    valueGbp: 120,
    valueKg: 0,
    url: 'https://www.ofcom.org.uk/phones-and-broadband/saving-money/social-tariffs',
    source: 'Ofcom social tariffs — mobile as well as broadband',
    verifiedOn: '2026-07-31',
    gates: { financial: ['TIGHT', 'GETTING_BY'] },
  },
  {
    id: 'out-of-contract-broadband',
    action: 'Check if you are out of contract',
    detail: 'Out-of-contract broadband quietly costs far more than the same service on a new deal. Providers must now tell you when it ends.',
    verb: 'SWITCH',
    cost: 'FREE',
    recurrence: 'ANNUAL',
    bucket: 'tech',
    valueGbp: 180,
    valueKg: 0,
    url: 'https://www.ofcom.org.uk/phones-and-broadband/saving-money/broadband-and-phone-contracts',
    source: 'Ofcom end-of-contract notifications',
    verifiedOn: '2026-07-31',
  },
  {
    id: 'prescription-prepayment',
    action: 'Get a prescription prepayment certificate',
    detail: 'Caps what you pay for prescriptions. Worth it from roughly three items a quarter in England.',
    verb: 'CLAIM',
    cost: 'LOW',
    recurrence: 'ANNUAL',
    bucket: 'money',
    valueGbp: 100,
    valueKg: 0,
    url: 'https://www.nhsbsa.nhs.uk/help-nhs-prescription-costs/prescription-prepayment-certificates-ppcs',
    source: 'NHSBSA prescription prepayment certificates',
    verifiedOn: '2026-07-31',
    gates: { countries: ['ENGLAND'] },
  },
  {
    id: 'charity-grant-search',
    action: 'Search charitable grants you can get',
    detail:
      'Thousands of small UK charities give one-off grants by occupation, county or circumstance, and almost nobody searches them.',
    verb: 'CLAIM',
    cost: 'FREE',
    recurrence: 'ANNUAL',
    bucket: 'money',
    valueGbp: 400,
    valueKg: 0,
    url: 'https://grants-search.turn2us.org.uk/',
    source: 'Turn2us grants search — UK charitable grant directory',
    verifiedOn: '2026-07-31',
    gates: { financial: ['TIGHT', 'GETTING_BY'] },
  },
  {
    id: 'lost-accounts-trace',
    action: 'Trace lost bank and pension money',
    detail: 'Free official tracing for forgotten accounts, and there are billions sitting unclaimed.',
    verb: 'CLAIM',
    cost: 'FREE',
    recurrence: 'ONCE',
    bucket: 'money',
    valueGbp: 200,
    valueKg: 0,
    url: 'https://www.mylostaccount.org.uk/',
    source: 'My Lost Account — UK Finance / BSA / NS&I joint free tracing service',
    verifiedOn: '2026-07-31',
  },
  {
    id: 'shared-bills-check',
    action: 'Check the bills split in your houseshare',
    detail: 'In shared homes the named bill-payer often quietly absorbs standing charges after someone moves out.',
    verb: 'DO',
    cost: 'FREE',
    recurrence: 'ANNUAL',
    bucket: 'utilities',
    valueGbp: 120,
    valueKg: 0,
    url: 'https://www.citizensadvice.org.uk/consumer/energy/energy-supply/your-energy-meter/who-is-responsible-for-paying-the-energy-bill/',
    source: 'Citizens Advice — responsibility for energy bills in shared housing',
    verifiedOn: '2026-07-31',
    requires: { household: ['SHARED'] },
  },
  {
    id: 'shorter-shower',
    action: 'Take four minutes off your shower',
    detail: 'Hot water is the second biggest energy use in most homes. Costs nothing and needs no kit.',
    verb: 'DO',
    cost: 'FREE',
    recurrence: 'ONGOING',
    bucket: 'water',
    valueGbp: 70,
    valueKg: 150,
    url: 'https://www.waterwise.org.uk/save-water/',
    source: 'Waterwise — shower duration and hot water use',
    verifiedOn: '2026-07-31',
    requires: { wash: ['SHOWER', 'BOTH'] },
  },
  {
    id: 'shallower-bath',
    action: 'Run your bath an inch shallower',
    detail: 'Around five litres of hot water saved per bath, with nothing bought and nothing installed.',
    verb: 'DO',
    cost: 'FREE',
    recurrence: 'ONGOING',
    bucket: 'water',
    valueGbp: 50,
    valueKg: 100,
    url: 'https://www.waterwise.org.uk/save-water/',
    source: 'Waterwise — an inch shallower saves ~5 litres per bath',
    verifiedOn: '2026-07-31',
    requires: { wash: ['BATH', 'BOTH'] },
  },
  {
    id: 'cancel-unused-subscriptions',
    action: 'Cancel the subscriptions you forgot',
    detail: 'Check the recurring payments list in your banking app. Most people find at least one they no longer use.',
    verb: 'DO',
    cost: 'FREE',
    recurrence: 'ANNUAL',
    bucket: 'money',
    valueGbp: 200,
    valueKg: 0,
    url: 'https://www.moneyhelper.org.uk/en/everyday-money/budgeting/how-to-cancel-a-subscription',
    source: 'MoneyHelper (MaPS) — cancelling subscriptions and continuous payment authorities',
    verifiedOn: '2026-07-31',
  },
  {
    id: 'community-food-club',
    action: 'Join a local food club',
    detail: 'Pantries and food clubs charge a few pounds for a basket worth several times that. No referral needed.',
    verb: 'DO',
    cost: 'FREE',
    recurrence: 'ONGOING',
    bucket: 'food',
    valueGbp: 400,
    valueKg: 200,
    url: 'https://www.familyaction.org.uk/food-clubs/',
    source: 'Family Action food clubs — membership-based community pantries',
    verifiedOn: '2026-07-31',
    gates: { financial: ['TIGHT'] },
    priorityBoost: 15,
  },
  {
    id: 'led-bulb-swap',
    action: 'Swap your most-used bulbs for LED',
    detail: 'Around a tenth of the running cost of halogen, and they come with you when you move.',
    verb: 'BUY',
    cost: 'LOW',
    recurrence: 'ONCE',
    bucket: 'home',
    valueGbp: 55,
    valueKg: 130,
    url: 'https://energysavingtrust.org.uk/advice/lighting/',
    source: 'Energy Saving Trust lighting guidance',
    verifiedOn: '2026-07-31',
  },
  {
    id: 'washing-machine-30',
    action: 'Wash at 30 and skip half loads',
    detail: 'Most of a wash cycle’s energy goes on heating water. Costs nothing to change.',
    verb: 'DO',
    cost: 'FREE',
    recurrence: 'ONGOING',
    bucket: 'utilities',
    valueGbp: 40,
    valueKg: 90,
    url: 'https://energysavingtrust.org.uk/advice/reducing-your-energy-use-at-home/',
    source: 'Energy Saving Trust — appliance energy use',
    verifiedOn: '2026-07-31',
  },

  // ---------------------------------------------------------------------------------------
  // Owner-only and paid actions. Present so the ranker has something to exclude and so the
  // other columns aren't empty — every one carries a renter exclusion.
  // ---------------------------------------------------------------------------------------
  {
    id: 'loft-insulation',
    action: 'Insulate the loft',
    detail: 'Cuts heat loss through the roof, the single largest escape route in most houses.',
    verb: 'BUY',
    cost: 'HIGH',
    recurrence: 'ONCE',
    bucket: 'home',
    valueGbp: 250,
    valueKg: 900,
    url: 'https://www.gov.uk/improve-energy-efficiency',
    source: 'GOV.UK find ways to save energy in your home',
    verifiedOn: '2026-07-31',
    requires: { tenure: ['OWNER'] },
    // A renter cannot act on this at any price. Hard exclusion, never a ranking penalty.
    excludes: { tenure: ['RENTER'] },
  },
  {
    id: 'solar-export-guarantee',
    action: 'Get paid for exported solar',
    detail:
      'Every large supplier must offer a Smart Export Guarantee tariff for power your panels send back.',
    verb: 'CLAIM',
    cost: 'HIGH',
    recurrence: 'ONCE',
    bucket: 'solar',
    valueGbp: 400,
    valueKg: 800,
    url: 'https://www.ofgem.gov.uk/environmental-and-social-schemes/smart-export-guarantee-seg',
    source: 'Ofgem Smart Export Guarantee',
    verifiedOn: '2026-07-31',
    requires: { tenure: ['OWNER'] },
    excludes: { tenure: ['RENTER'] },
  },
  {
    id: 'boiler-upgrade-scheme',
    action: 'Use the Boiler Upgrade Scheme',
    detail: 'A government grant toward replacing a gas boiler with a heat pump.',
    verb: 'CLAIM',
    cost: 'HIGH',
    recurrence: 'ONCE',
    bucket: 'home',
    valueGbp: 300,
    valueKg: 1200,
    url: 'https://www.gov.uk/apply-boiler-upgrade-scheme',
    source: 'GOV.UK Boiler Upgrade Scheme',
    verifiedOn: '2026-07-31',
    requires: { tenure: ['OWNER'], heating: ['GAS'] },
    excludes: { tenure: ['RENTER'] },
  },
  {
    id: 'low-flow-shower-head',
    action: 'Fit a flow-limited shower head',
    detail: 'Cuts hot water use without losing pressure, and unscrews again when you move out.',
    verb: 'BUY',
    cost: 'LOW',
    recurrence: 'ONCE',
    bucket: 'water',
    valueGbp: 80,
    valueKg: 120,
    url: 'https://www.waterwise.org.uk/save-water/',
    source: 'Waterwise — an efficient shower head could reduce household bills by up to £120/yr',
    verifiedOn: '2026-07-31',
    gates: { wash: ['SHOWER', 'BOTH'] },
  },
  {
    id: 'refurbished-tech',
    action: 'Buy refurbished, not new',
    detail: 'Up to 70% below new, with a 12-month warranty and 30-day returns.',
    verb: 'BUY',
    cost: 'HIGH',
    recurrence: 'ONGOING',
    bucket: 'tech',
    valueGbp: 200,
    valueKg: 150,
    url: 'https://www.backmarket.co.uk/en-gb',
    source: 'Back Market UK — refurbished marketplace, 12-month warranty',
    verifiedOn: '2026-07-31',
  },
  {
    id: 'railcard',
    action: 'Get a railcard',
    detail: 'A third off most fares for £30 a year, which pays for itself in about two trips.',
    verb: 'BUY',
    cost: 'LOW',
    recurrence: 'ANNUAL',
    bucket: 'travel',
    valueGbp: 167,
    valueKg: 200,
    url: 'https://www.railcard.co.uk/',
    source: 'Railcard.co.uk — 1/3 off, £30/yr; Trainline cites £167 average annual saving',
    verifiedOn: '2026-07-31',
    gates: { transport: ['PUBLIC', 'MIX', 'CAR'] },
  },
  {
    id: 'ethical-isa',
    action: 'Move savings somewhere fossil-free',
    detail: 'Triodos publishes every organisation it finances, and its cash ISA is FSCS protected.',
    verb: 'SWITCH',
    cost: 'HIGH',
    recurrence: 'ONCE',
    bucket: 'money',
    valueGbp: 0,
    valueKg: 400,
    url: 'https://www.triodos.co.uk/ethical-isas',
    source: 'Triodos Bank UK — ethical ISA range, FSCS protected to £120k',
    verifiedOn: '2026-07-31',
    gates: { financial: ['DOING_OK'] },
    // Suggesting where to park savings to someone with none is the clearest possible signal
    // that the app has not listened.
    excludes: { financial: ['TIGHT'] },
  },
]
